# Generated by Django 4.2.28 on 2026-04-10 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import edxval.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("edxval", "0004_add_edx_ai_translations_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAudioDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "audio_description_file",
                    edxval.models.CustomizableAudioDescriptionFileField(
                        blank=True, null=True
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("mp3", "MP3"),
                            ("m4a", "M4A"),
                            ("wav", "WAV"),
                            ("aac", "AAC"),
                            ("ogg", "OGG"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_description",
                        to="edxval.video",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
