# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import edxval.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edxval', '0006_auto_20170823_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(max_length=255, unique=True, verbose_name=b'Course ID')),
                ('provider', models.CharField(choices=[(b'Custom', b'Custom'), (b'3PlayMedia', b'3PlayMedia'), (b'Cielo24', b'Cielo24')], max_length=20, verbose_name=b'Provider')),
                ('cielo24_fidelity', models.CharField(blank=True, choices=[(b'MECHANICAL', b'Mechanical, 75% Accuracy'), (b'PREMIUM', b'Premium, 95% Accuracy'), (b'PROFESSIONAL', b'Professional, 99% Accuracy')], max_length=20, null=True, verbose_name=b'Cielo24 Fidelity')),
                ('cielo24_turnaround', models.CharField(blank=True, choices=[(b'STANDARD', b'Standard, 48h'), (b'PRIORITY', b'Priority, 24h')], max_length=20, null=True, verbose_name=b'Cielo24 Turnaround')),
                ('three_play_turnaround', models.CharField(blank=True, choices=[(b'extended_service', b'10-Day/Extended'), (b'default', b'4-Day/Default'), (b'expedited_service', b'2-Day/Expedited'), (b'rush_service', b'24 hour/Rush'), (b'same_day_service', b'Same Day')], max_length=20, null=True, verbose_name=b'3PlayMedia Turnaround')),
                ('preferred_languages', edxval.models.ListField(blank=True, default=[], max_items=50, verbose_name=b'Preferred Languages')),
                ('video_source_language', models.CharField(blank=True, help_text=b'This is the source language of a video.', max_length=20, null=True, verbose_name=b'Video Source Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
