name: Upgrade Requirements

on:
  schedule:
    - cron: "15 2 * * 5"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: "master"

jobs:
  call-upgrade-python-requirements-workflow:
    uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@master
    with:
      branch: ${{ github.event.inputs.branch }}
      # user_reviewers: ""
      # team_reviewers: '2u-aurora'
      email_address: "aurora-requirements-update@2u-internal.opsgenie.net"
      end_success_notification: true
    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
